### ISSUE TITLE
Adapter stürzt immer wieder ab

### ISSUE THREAD

**Issue by crusader85** [tp1de/ioBroker.ems-esp#21]
Hallo, 

leider stürzt der Adapter nach ein paar Minuten ab. Ich nutze nur die KM200

```
ems-esp.0 | 2023-07-13 15:04:12.460 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
ems-esp.0 | 2023-07-13 15:04:12.459 | info | terminating
ems-esp.0 | 2023-07-13 15:04:12.456 | error | Parameter "instanceName" needs to be of type "string" but type "undefined" has been passed
ems-esp.0 | 2023-07-13 15:04:12.454 | error | Error: Parameter "instanceName" needs to be of type "string" but type "undefined" has been passed at Validator.assertString (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/validator.js:168:19) at AdapterClass.sendTo (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5014:31) at enable_state (/opt/iobroker/node_modules/iobroker.ems-esp/main.js:121:10) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.ems-esp/main.js:330:38) at process.processImmediate (node:internal/timers:473:21)
ems-esp.0 | 2023-07-13 15:04:12.453 | error | uncaught exception: Parameter "instanceName" needs to be of type "string" but type "undefined" has been passed
ems-esp.0 | 2023-07-13 15:03:12.449 | info | km200:true 300 secs
ems-esp.0 | 2023-07-13 15:03:12.449 | info | end of initializing km200 states
ems-esp.0 | 2023-07-13 15:02:45.380 | info | start initializing km200 states
ems-esp.0 | 2023-07-13 15:02:45.379 | info | write km200 file:/opt/iobroker/iobroker-data//ems-esp/0/km200.csv
ems-esp.0 | 2023-07-13 15:02:45.379 | info | End reading km200 data-structure: 109 fields found
ems-esp.0 | 2023-07-13 15:02:12.397 | info | start reading km200 data-structure
ems-esp.0 | 2023-07-13 15:02:12.071 | info | starting. Version 1.31.0 in /opt/iobroker/node_modules/iobroker.ems-esp, node: v18.7.0, js-controller: 5.0.7
```

Vielen Dank und Grüße :)

**Comment by tp1de** [comment]
Was soll ich sagen, ohne die Screenshots der Adapter Parameter ???

**Comment by tp1de** [comment]
Nimm bitte die Datenbank raus

**Comment by tp1de** [comment]
Statistiken gehen nur mit Datenbak wie in der Readme beschrieben ... dazu brauchst Du eine akltive DB-Instanz

**Comment by tp1de** [comment]
Ich habe die Überprüfung im Adapter angepasst.
